import type {
  ContextItemPreview,
  ContextPreview,
  EventPayload,
  IpcError,
  ItemKind,
  ThreadSummary,
} from "@kalcode/protocol";
import type { ContextInput, ContextSendResult } from "../context.ts";
import type { DashboardHandlers } from "./dashboard.ts";

const MAX_ITEMS = 24;
const MAX_ITEM_CHARS = 256_000;
const MAX_TOTAL_BYTES = 512 * 1024;
const NON_SENDABLE = new Set<ThreadSummary["status"]>([
  "waiting_for_permission",
  "paused",
  "completed",
  "failed",
  "interrupted",
  "offline",
]);
const UNCERTAIN_DELIVERY = new Set<ThreadSummary["status"]>(["failed", "offline", "interrupted"]);

type Lifecycle = "draft" | "validating" | "sending" | "failed_uncertain";

interface TargetSnapshot {
  threadId: string;
  providerId: string;
  providerAccountId: string | null;
  workspaceId: string;
}

interface PackageRecord {
  lifecycle: Lifecycle;
  target: TargetSnapshot;
  preview: ContextPreview;
  renderedItems: string[];
  rendered: string;
}

export interface ContextMemoryDependencies {
  getThread(threadId: string): ThreadSummary;
  sendThread(
    threadId: string,
    userText: string,
    providerPayload: string,
    promptReviewId: string | null,
  ): Promise<ThreadSummary>;
  emit(event: EventPayload): unknown;
}

function fail(code: string, message: string, retryable = false): never {
  throw { category: "validation", code, message, retryable } satisfies IpcError;
}

function requiredString(value: unknown, code: string, max: number): string {
  if (typeof value !== "string" || !value.trim() || value.length > max) {
    fail(code, "The context request is invalid.");
  }
  return value.trim();
}

function promptConfirmationFailure(error: unknown): boolean {
  if (!error || typeof error !== "object") return false;
  const code = (error as { code?: unknown }).code;
  return code === "context_prompt_confirmation_required" || code === "context_prompt_confirmation_invalid";
}

function targetOf(thread: ThreadSummary): TargetSnapshot {
  if (thread.archivedAt || NON_SENDABLE.has(thread.status)) {
    fail("context_target_inactive", "Context can only be sent to an active thread.");
  }
  return {
    threadId: thread.id,
    providerId: thread.providerId,
    providerAccountId: thread.providerAccountId,
    workspaceId: thread.workspaceId,
  };
}

function sameTarget(left: TargetSnapshot, right: TargetSnapshot): boolean {
  return (
    left.threadId === right.threadId &&
    left.providerId === right.providerId &&
    left.providerAccountId === right.providerAccountId &&
    left.workspaceId === right.workspaceId
  );
}

/** Deterministic fixture hash. Production hashes are generated by the Rust ContextPackage. */
function fixtureHash(value: string): string {
  let hash = 0x811c9dc5;
  for (let index = 0; index < value.length; index += 1) {
    hash ^= value.charCodeAt(index);
    hash = Math.imul(hash, 0x01000193) >>> 0;
  }
  return hash.toString(16).padStart(8, "0").repeat(8);
}

interface EvaluatedInput {
  item: ContextItemPreview;
  rendered: string;
  redactions: number;
}

const CREDENTIAL_ASSIGNMENT = /\b(password|passwd|pwd|api[_-]?key|access[_-]?token|secret)\s*[:=]\s*([^\s,;]+)/gi;
const CONTROL_CHARACTER = /\p{Cc}/u;

function redactFixtureText(value: string): { text: string; redactions: number } {
  let redactions = 0;
  const text = value.replace(CREDENTIAL_ASSIGNMENT, (_match, key: string) => {
    redactions += 1;
    return `${key}=[REDACTED]`;
  });
  return { text, redactions };
}

function validPrompt(value: unknown): string {
  if (typeof value !== "string" || !value.trim() || value.includes("\0")) {
    fail("invalid_prompt", "Write a valid message before sending context.");
  }
  if ([...value].length > 100_000) {
    fail("invalid_prompt", "That message is too long. Keep it under 100,000 characters.");
  }
  return value.trimEnd();
}

function evaluateText(
  input: Extract<ContextInput, { kind: "text" | "selection" | "log_output" }>,
  position: number,
): EvaluatedInput {
  const rawLabel = requiredString(input.label, "context_label_invalid", 120);
  if ([...rawLabel].some((character) => CONTROL_CHARACTER.test(character))) {
    fail("context_label_invalid", "That context value isn't valid.");
  }
  if (typeof input.text !== "string" || input.text.length > MAX_ITEM_CHARS) {
    fail("context_item_too_large", "That context item is too large.");
  }
  const text = input.text.replace(/\r\n/g, "\n");
  const safeLabel = redactFixtureText(rawLabel);
  const safeBody = redactFixtureText(text);
  const label = safeLabel.text;
  const safe = safeBody.text;
  const redactions = safeLabel.redactions + safeBody.redactions;
  const bytes = new TextEncoder().encode(safe).byteLength;
  const kind: ItemKind = input.kind;
  return {
    rendered: safe,
    redactions,
    item: {
      position,
      label,
      kind,
      sourceKind: input.kind === "text" ? "inline_text" : input.kind,
      bytes,
      sensitivity: redactions > 0 ? "secret" : "internal",
      verdict: redactions > 0 ? { kind: "allow_redacted", spans: redactions } : { kind: "allow" },
      rules:
        redactions > 0
          ? [
              {
                rule: { kind: "secret_detected", detector: "credential_assignment", count: redactions },
                effect: "redact",
                message: "A credential-shaped value was removed before sharing.",
              },
            ]
          : [],
      excerpt: safe.slice(0, 4096),
      included: true,
      overridable: false,
      overrideConfirmed: false,
      translation: { kind: "inline", bytes },
      note: null,
      unavailable: null,
    },
  };
}

function evaluateUrl(input: Extract<ContextInput, { kind: "url" }>, position: number): EvaluatedInput {
  const raw = requiredString(input.url, "context_url_invalid", 2_048);
  let url: URL;
  try {
    url = new URL(raw);
  } catch {
    fail("context_url_invalid", "Enter a valid http or https URL.");
  }
  if (url.protocol !== "http:" && url.protocol !== "https:") {
    fail("context_url_invalid", "Only http and https URL references can be shared.");
  }
  const redactions = url.username || url.password ? 1 : 0;
  url.username = "";
  url.password = "";
  const safe = url.toString();
  const bytes = new TextEncoder().encode(safe).byteLength;
  return {
    rendered: safe,
    redactions,
    item: {
      position,
      label: url.hostname,
      kind: "url_reference",
      sourceKind: "url_reference",
      bytes,
      sensitivity: redactions > 0 ? "secret" : "public",
      verdict: redactions > 0 ? { kind: "allow_redacted", spans: redactions } : { kind: "allow" },
      rules:
        redactions > 0
          ? [
              {
                rule: { kind: "secret_detected", detector: "url_credentials", count: redactions },
                effect: "redact",
                message: "Credentials were removed from the URL before sharing.",
              },
            ]
          : [],
      excerpt: safe,
      included: true,
      overridable: false,
      overrideConfirmed: false,
      translation: { kind: "inline", bytes },
      note: "URL reference only. KalCode does not fetch it.",
      unavailable: null,
    },
  };
}

function renderIncluded(items: ContextItemPreview[], renderedItems: string[]): string {
  return items
    .map((item, index) => ({ item, content: renderedItems[index] ?? "" }))
    .filter(({ item }) => item.included)
    .map(({ item, content }) => `--- ${item.label} (${item.kind}) ---\n${content}`)
    .join("\n\n");
}

function refreshRecord(record: PackageRecord): ContextPreview {
  record.rendered = renderIncluded(record.preview.items, record.renderedItems);
  record.preview = {
    ...record.preview,
    totalBytes: record.preview.items.filter((item) => item.included).reduce((sum, item) => sum + item.bytes, 0),
    contentSha256: fixtureHash(record.rendered),
  };
  return record.preview;
}

function build(
  thread: ThreadSummary,
  inputs: ContextInput[],
): {
  preview: ContextPreview;
  renderedItems: string[];
  rendered: string;
  redactions: number;
} {
  if (!Array.isArray(inputs) || inputs.length === 0 || inputs.length > MAX_ITEMS) {
    fail("context_items_invalid", `Add between 1 and ${MAX_ITEMS} context items.`);
  }
  const evaluated = inputs.map((input, position) => {
    if (input.kind === "text" || input.kind === "selection" || input.kind === "log_output") {
      return evaluateText(input, position);
    }
    if (input.kind === "url") return evaluateUrl(input, position);
    // The memory transport cannot dereference native file handles. Native owns this path.
    return fail("context_file_unavailable", "Files can only be previewed by the installed desktop runtime.");
  });
  const totalBytes = evaluated.reduce((sum, value) => sum + value.item.bytes, 0);
  if (totalBytes > MAX_TOTAL_BYTES) fail("context_package_too_large", "The context package is too large.");
  const packageId = crypto.randomUUID();
  const renderedItems = evaluated.map(({ rendered }) => rendered);
  const rendered = renderIncluded(
    evaluated.map(({ item }) => item),
    renderedItems,
  );
  const contentSha256 = fixtureHash(rendered);
  return {
    rendered,
    renderedItems,
    redactions: evaluated.reduce((sum, item) => sum + item.redactions, 0),
    preview: {
      packageId,
      purpose: "drop",
      targetProviderId: thread.providerId,
      targetThreadId: thread.id,
      items: evaluated.map((value) => value.item),
      totalBytes,
      maxBytes: MAX_TOTAL_BYTES,
      translationNotes: [],
      contentSha256,
    },
  };
}

export function createContextMemory({ getThread, sendThread, emit }: ContextMemoryDependencies): {
  handlers: DashboardHandlers;
} {
  const packages = new Map<string, PackageRecord>();

  const handlers: DashboardHandlers = {
    context_preview_create(args) {
      const threadId = requiredString(args.threadId, "context_thread_invalid", 128);
      const thread = getThread(threadId);
      const target = targetOf(thread);
      const built = build(thread, args.inputs as ContextInput[]);
      packages.set(built.preview.packageId, {
        lifecycle: "draft",
        target,
        preview: built.preview,
        renderedItems: built.renderedItems,
        rendered: built.rendered,
      });
      emit({
        type: "context.package_created",
        payload: {
          packageId: built.preview.packageId,
          purpose: "drop",
          items: built.preview.items.length,
          bytes: built.preview.totalBytes,
        },
      });
      if (built.redactions > 0) {
        emit({
          type: "context.redacted",
          payload: { packageId: built.preview.packageId, items: 1, spans: built.redactions },
        });
      }
      return built.preview;
    },
    context_file_pick() {
      // Native owns the OS picker and issues opaque, workspace-bound file handles.
      return [];
    },
    context_item_set(args) {
      const packageId = requiredString(args.packageId, "context_package_invalid", 128);
      const record = packages.get(packageId);
      if (!record) fail("context_package_unknown", "That context preview is no longer available.");
      if (record.lifecycle !== "draft")
        fail("context_package_locked", "That context preview can no longer be changed.");
      const position = Number(args.position);
      if (!Number.isInteger(position) || position < 0 || position >= record.preview.items.length) {
        fail("context_item_invalid", "That context item is no longer available.");
      }
      if (typeof args.included !== "boolean") fail("context_item_invalid", "That context selection is invalid.");
      record.preview = {
        ...record.preview,
        items: record.preview.items.map((item) =>
          item.position === position ? { ...item, included: args.included as boolean } : item,
        ),
      };
      return refreshRecord(record);
    },
    context_item_confirm(args) {
      const packageId = requiredString(args.packageId, "context_package_invalid", 128);
      const record = packages.get(packageId);
      if (!record) fail("context_package_unknown", "That context preview is no longer available.");
      const position = Number(args.position);
      const item = record.preview.items.find((candidate) => candidate.position === position);
      if (!item?.overridable) fail("context_override_not_allowed", "That context item cannot be overridden.");
      record.preview = {
        ...record.preview,
        items: record.preview.items.map((candidate) =>
          candidate.position === position ? { ...candidate, overrideConfirmed: true, included: true } : candidate,
        ),
      };
      emit({
        type: "context.override_confirmed",
        payload: { packageId, position, rule: "user_confirmation" },
      });
      return refreshRecord(record);
    },
    context_discard(args) {
      const packageId = requiredString(args.packageId, "context_package_invalid", 128);
      const record = packages.get(packageId);
      if (!record) fail("context_package_unknown", "That context preview is no longer available.");
      if (record.lifecycle === "validating" || record.lifecycle === "sending") {
        fail("context_send_in_progress", "This context is already being sent.");
      }
      packages.delete(packageId);
      emit({ type: "context.discarded", payload: { packageId } });
    },
    async context_send(args): Promise<ContextSendResult> {
      const packageId = requiredString(args.packageId, "context_package_invalid", 128);
      const threadId = requiredString(args.threadId, "context_thread_invalid", 128);
      const text = validPrompt(args.text);
      const promptReviewId =
        args.promptReviewId == null
          ? null
          : requiredString(args.promptReviewId, "context_prompt_confirmation_invalid", 128);
      const previewedSha256 = requiredString(args.previewedSha256, "context_hash_invalid", 128);
      const record = packages.get(packageId);
      if (!record) fail("context_package_unknown", "That context preview is no longer available.");
      if (record.lifecycle === "validating" || record.lifecycle === "sending") {
        fail("context_send_in_progress", "This context is already being sent.");
      }
      if (record.lifecycle === "failed_uncertain") {
        fail("context_send_uncertain", "The provider outcome is unknown. Review the thread before sending again.");
      }
      if (threadId !== record.target.threadId) fail("context_target_changed", "The context target changed.");
      const current = targetOf(getThread(threadId));
      if (!sameTarget(record.target, current)) fail("context_target_changed", "The context target changed.");
      if (previewedSha256 !== record.preview.contentSha256) {
        return { kind: "stale", preview: record.preview };
      }
      if (!record.rendered) fail("context_nothing_to_send", "Select at least one context item before sending.");

      record.lifecycle = "validating";
      let providerPayload: string;
      try {
        providerPayload = validPrompt(`${text}\n\nContext supplied by you:\n${record.rendered}`);
      } catch (error) {
        record.lifecycle = "draft";
        throw error;
      }

      // Validation completed while edits were reserved. This is the irreversible one-shot claim.
      record.lifecycle = "sending";
      try {
        const thread = await sendThread(threadId, text, providerPayload, promptReviewId);
        if (UNCERTAIN_DELIVERY.has(thread.status)) {
          fail("context_send_uncertain", "The provider outcome is unknown. Review the thread before sending again.");
        }
        packages.delete(packageId);
        emit({
          type: "context.shared",
          payload: {
            packageId,
            threadId,
            providerId: record.target.providerId,
            items: record.preview.items.filter((item) => item.included).length,
            bytes: record.preview.totalBytes,
            redactions: record.preview.items.reduce(
              (sum, item) => sum + (item.verdict.kind === "allow_redacted" ? item.verdict.spans : 0),
              0,
            ),
          },
        });
        return { kind: "sent", thread };
      } catch (error) {
        if (promptConfirmationFailure(error)) {
          record.lifecycle = "draft";
          throw error;
        }
        record.lifecycle = "failed_uncertain";
        fail("context_send_uncertain", "The provider outcome is unknown. Review the thread before sending again.");
      }
    },
  };
  return { handlers };
}
