//! Cross-language vectors: tokens signed in TypeScript by the API signer (WebCrypto Ed25519),
//! verified here by the desktop verifier. Generated by `apps/api/tests/unit/vectors.test.ts`,
//! which checks the same file against the TypeScript verifier and evaluator.

// Test-only helpers (outside #[test] fns) fail loudly on bad fixture data by design.
#![allow(clippy::expect_used)]

use std::collections::BTreeMap;

use ed25519_dalek::{Signature, Signer, SigningKey, VerifyingKey};
use kalcode_entitlements::{
    CLOCK_SKEW_SECONDS, CachedEntitlement, DOCUMENT_VERSION, EntitlementStatus, Grants,
    KalVoiceDecision, Limit, MAX_DOCUMENT_LIFETIME_SECONDS, MAX_TOKEN_LENGTH, TOKEN_ALGORITHM,
    TOKEN_TYPE, Tier, USAGE_RECEIPT_MAX_LIFETIME_SECONDS, USAGE_TOKEN_TYPE, Verifier, VerifyError,
};
use serde::Deserialize;
use time::OffsetDateTime;

const VECTORS: &str = include_str!("../testdata/vectors.json");

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Vectors {
    constants: Constants,
    free_grants: Grants,
    keys: Vec<Key>,
    rfc8032: Vec<Rfc8032>,
    cases: Vec<Case>,
    receipt_cases: Vec<ReceiptCase>,
}

#[derive(Deserialize)]
struct ReceiptCase {
    name: String,
    token: String,
    now: i64,
    expect: ReceiptExpect,
}

#[derive(Deserialize)]
struct ReceiptExpect {
    ok: bool,
    error: Option<String>,
    receipt: Option<serde_json::Value>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Constants {
    document_version: u32,
    max_document_lifetime_seconds: i64,
    clock_skew_seconds: i64,
    max_token_length: usize,
    token_type: String,
    usage_token_type: String,
    usage_receipt_max_lifetime_seconds: i64,
    algorithm: String,
}

#[derive(Deserialize)]
struct Key {
    kid: String,
    x: String,
}

#[derive(Deserialize)]
struct Rfc8032 {
    secret: String,
    public: String,
    message: String,
    signature: String,
}

#[derive(Deserialize)]
struct Case {
    name: String,
    token: String,
    now: i64,
    expect: Expect,
}

#[derive(Deserialize)]
struct Expect {
    ok: bool,
    error: Option<String>,
    entitlement: Option<serde_json::Value>,
    features: Option<BTreeMap<String, bool>>,
    limits: Option<BTreeMap<String, Option<u64>>>,
}

fn vectors() -> Vectors {
    serde_json::from_str(VECTORS).expect("vectors.json parses")
}

fn verifier(vectors: &Vectors) -> Verifier {
    Verifier::from_keys(
        vectors
            .keys
            .iter()
            .map(|key| (key.kid.as_str(), key.x.as_str())),
    )
    .expect("vector keys")
}

fn hex(value: &str) -> Vec<u8> {
    (0..value.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&value[i..i + 2], 16).expect("hex"))
        .collect()
}

#[test]
fn constants_match_the_typescript_protocol() {
    let v = vectors();
    assert_eq!(v.constants.document_version, DOCUMENT_VERSION);
    assert_eq!(
        v.constants.max_document_lifetime_seconds,
        MAX_DOCUMENT_LIFETIME_SECONDS
    );
    assert_eq!(v.constants.clock_skew_seconds, CLOCK_SKEW_SECONDS);
    assert_eq!(v.constants.max_token_length, MAX_TOKEN_LENGTH);
    assert_eq!(v.constants.token_type, TOKEN_TYPE);
    assert_eq!(v.constants.usage_token_type, USAGE_TOKEN_TYPE);
    assert_eq!(
        v.constants.usage_receipt_max_lifetime_seconds,
        USAGE_RECEIPT_MAX_LIFETIME_SECONDS
    );
    assert_eq!(v.constants.algorithm, TOKEN_ALGORITHM);
    assert_eq!(
        v.free_grants,
        Grants::free(),
        "Free fallback must equal the public catalog's Free plan"
    );
}

#[test]
fn every_vector_verifies_exactly_as_in_typescript() {
    let v = vectors();
    let verifier = verifier(&v);
    assert!(v.cases.len() >= 20);
    for case in &v.cases {
        let result = verifier.verify(&case.token, case.now);
        if case.expect.ok {
            let entitlement =
                result.unwrap_or_else(|e| panic!("{}: expected valid, got {e:?}", case.name));
            let expected = case.expect.entitlement.clone().expect("entitlement");
            assert_eq!(
                serde_json::to_value(&entitlement).expect("serialize"),
                expected,
                "{}",
                case.name
            );
            for (feature, granted) in case.expect.features.as_ref().expect("features") {
                assert_eq!(
                    entitlement.has_feature(feature),
                    *granted,
                    "{}: {feature}",
                    case.name
                );
            }
            for (limit, value) in case.expect.limits.as_ref().expect("limits") {
                let expected = value.map_or(Limit::Unlimited, Limit::AtMost);
                assert_eq!(entitlement.limit(limit), expected, "{}: {limit}", case.name);
            }
        } else {
            let error = result.expect_err(&case.name);
            assert_eq!(
                Some(error.code()),
                case.expect.error.as_deref(),
                "{}",
                case.name
            );
        }
    }
}

#[test]
fn owner_vector_grants_the_future() {
    let v = vectors();
    let owner = v
        .cases
        .iter()
        .find(|c| c.name == "owner")
        .expect("owner vector");
    let entitlement = verifier(&v).verify(&owner.token, owner.now).expect("valid");
    assert_eq!(entitlement.tier, Tier::Owner);
    assert!(entitlement.unrestricted);
    assert!(entitlement.has_feature("featureAddedInTheFuture"));
    assert_eq!(entitlement.limit("limitAddedInTheFuture"), Limit::Unlimited);
}

#[test]
fn effective_entitlement_applies_owner_only_for_the_signed_in_account() {
    let v = vectors();
    let verifier = verifier(&v);
    let owner = v
        .cases
        .iter()
        .find(|c| c.name == "owner")
        .expect("owner vector");
    let account_id = owner
        .expect
        .entitlement
        .as_ref()
        .and_then(|e| e["accountId"].as_str())
        .expect("account");
    let at = |unix: i64| OffsetDateTime::from_unix_timestamp(unix).expect("time");

    let mine = CachedEntitlement {
        token: owner.token.clone(),
        account_id: account_id.to_owned(),
    };
    let effective = verifier.effective_entitlement(Some(&mine), at(owner.now));
    assert_eq!(effective.tier, Tier::Owner);
    assert!(effective.has_feature("featureAddedInTheFuture"));
    assert!(matches!(
        effective.status,
        EntitlementStatus::Verified { .. }
    ));

    // A copied document does not make another account OWNER.
    let theirs = CachedEntitlement {
        token: owner.token.clone(),
        account_id: "someone-else".into(),
    };
    let effective = verifier.effective_entitlement(Some(&theirs), at(owner.now));
    assert_eq!(
        (effective.tier, effective.status),
        (Tier::Free, EntitlementStatus::WrongAccount)
    );

    // Offline grace ends with the document: Free until the device fetches a fresh one.
    let expired = v
        .cases
        .iter()
        .find(|c| c.name == "owner-expired")
        .expect("expired vector");
    let effective = verifier.effective_entitlement(Some(&mine), at(expired.now));
    assert_eq!(effective.tier, Tier::Free);
    assert_eq!(
        effective.status,
        EntitlementStatus::Rejected(VerifyError::Expired)
    );
    assert_eq!(effective.limit("parallelAgents"), Limit::AtMost(1));

    // Production builds do not trust the test key.
    let production = kalcode_entitlements::effective_entitlement(Some(&mine), at(owner.now));
    assert_eq!(production.tier, Tier::Free);
    assert_eq!(
        production.status,
        EntitlementStatus::Rejected(VerifyError::UnknownKey)
    );
}

#[test]
fn ed25519_known_answers_rfc8032() {
    let v = vectors();
    assert_eq!(v.rfc8032.len(), 2);
    for vector in &v.rfc8032 {
        let secret: [u8; 32] = hex(&vector.secret).try_into().expect("32-byte secret");
        let public: [u8; 32] = hex(&vector.public).try_into().expect("32-byte public key");
        let expected: [u8; 64] = hex(&vector.signature)
            .try_into()
            .expect("64-byte signature");
        let message = hex(&vector.message);
        let signing = SigningKey::from_bytes(&secret);
        assert_eq!(signing.verifying_key().to_bytes(), public);
        assert_eq!(signing.sign(&message).to_bytes(), expected);
        let verifying = VerifyingKey::from_bytes(&public).expect("public key");
        assert!(
            verifying
                .verify_strict(&message, &Signature::from_bytes(&expected))
                .is_ok()
        );
        let mut tampered = expected;
        tampered[0] ^= 1;
        assert!(
            verifying
                .verify_strict(&message, &Signature::from_bytes(&tampered))
                .is_err()
        );
    }
}

#[test]
fn every_usage_receipt_verifies_exactly_as_in_typescript() {
    let v = vectors();
    let verifier = verifier(&v);
    assert!(v.receipt_cases.len() >= 9);
    for case in &v.receipt_cases {
        let result = verifier.verify_usage_receipt(&case.token, case.now);
        if case.expect.ok {
            let receipt =
                result.unwrap_or_else(|e| panic!("{}: expected valid, got {e:?}", case.name));
            let expected = case.expect.receipt.clone().expect("receipt");
            assert_eq!(
                serde_json::to_value(&receipt).expect("serialize"),
                expected,
                "{}",
                case.name
            );
        } else {
            let error = result.expect_err(&case.name);
            assert_eq!(
                Some(error.code()),
                case.expect.error.as_deref(),
                "{}",
                case.name
            );
        }
    }
}

#[test]
fn kalvoice_allowance_decisions_offline() {
    let v = vectors();
    let verifier = verifier(&v);
    let token = |name: &str| {
        v.cases
            .iter()
            .find(|c| c.name == name)
            .map(|c| (c.token.clone(), c.now))
            .expect("vector")
    };
    let receipt = |name: &str| {
        let case = v
            .receipt_cases
            .iter()
            .find(|c| c.name == name)
            .expect("receipt vector");
        verifier
            .verify_usage_receipt(&case.token, case.now)
            .expect("valid receipt")
    };
    let at = |unix: i64| OffsetDateTime::from_unix_timestamp(unix).expect("time");
    let effective = |name: &str, account: &str| {
        let (token, now) = token(name);
        let cached = CachedEntitlement {
            token,
            account_id: account.to_owned(),
        };
        verifier.effective_entitlement(Some(&cached), at(now))
    };
    let account = v.cases[0]
        .expect
        .entitlement
        .as_ref()
        .and_then(|e| e["accountId"].as_str())
        .expect("account")
        .to_owned();

    // Pro: 41 used of 150 per the signed receipt.
    let pro = effective("pro", &account);
    let pro_receipt = receipt("pro-receipt");
    assert_eq!(
        pro.kalvoice_decision(Some(&pro_receipt), 0),
        KalVoiceDecision::Allowed {
            remaining: Some(150 - 41 - 1)
        }
    );
    assert_eq!(
        pro.kalvoice_decision(Some(&pro_receipt), 150 - 41 - 1),
        KalVoiceDecision::Allowed { remaining: Some(0) }
    );
    assert_eq!(
        pro.kalvoice_decision(Some(&pro_receipt), 150 - 41),
        KalVoiceDecision::Denied {
            resets_at: Some("2026-10-10T08:00:00.000Z".into())
        }
    );
    // Without a receipt the provisional local count is checked against the plan allowance.
    assert_eq!(
        pro.kalvoice_decision(None, 149),
        KalVoiceDecision::Allowed { remaining: Some(0) }
    );
    assert_eq!(
        pro.kalvoice_decision(None, 150),
        KalVoiceDecision::Denied { resets_at: None }
    );

    // OWNER is never denied, whatever any receipt or local count says.
    let owner = effective("owner", &account);
    let exhausted = receipt("free-receipt-exhausted");
    for (r, unsynced) in [
        (None, u64::MAX),
        (Some(&exhausted), u64::MAX),
        (Some(&pro_receipt), 1_000_000),
    ] {
        assert_eq!(
            owner.kalvoice_decision(r, unsynced),
            KalVoiceDecision::Allowed { remaining: None }
        );
    }

    // Free fallback (no valid document): 25 per cycle, exhausted receipts are not trusted
    // without a verified account, so only the local count applies.
    let free = verifier.effective_entitlement(None, at(v.cases[0].now));
    assert_eq!(
        free.kalvoice_decision(Some(&exhausted), 0),
        KalVoiceDecision::Allowed {
            remaining: Some(24)
        }
    );
    assert_eq!(
        free.kalvoice_decision(None, 25),
        KalVoiceDecision::Denied { resets_at: None }
    );
    let signed_free = effective("free", &account);
    assert_eq!(
        signed_free.kalvoice_decision(Some(&exhausted), 0),
        KalVoiceDecision::Denied {
            resets_at: Some("2026-10-10T08:00:00.000Z".into())
        }
    );

    // A receipt for another account is ignored.
    let mut foreign = pro_receipt.clone();
    foreign.account_id = "someone-else".into();
    assert_eq!(
        pro.kalvoice_decision(Some(&foreign), 0),
        KalVoiceDecision::Allowed {
            remaining: Some(149)
        }
    );
}
