/**
 * Hero world images (generated by tooling/generate-hero-world.py into public/assets/hero/world).
 * Shared by HeroOrb (the <picture>) and the page head (a preload for the LCP image), so the
 * browser fetches exactly the file the layout uses.
 *
 * Preload example (index.astro head slot), one per media:
 *   <link rel="preload" as="image" type="image/avif" fetchpriority="high"
 *         media={WORLD_LANDSCAPE_MEDIA} imagesrcset={worldSrcset(WORLD_LANDSCAPE, "avif")}
 *         imagesizes={WORLD_SIZES} />
 *   <link rel="preload" as="image" type="image/avif" fetchpriority="high"
 *         media={WORLD_PORTRAIT_MEDIA} imagesrcset={worldSrcset(WORLD_PORTRAIT, "avif")}
 *         imagesizes="220vw" />
 */
export const WORLD_LANDSCAPE = { stem: "world", widths: [1280, 1920, 2560] } as const;
export const WORLD_PORTRAIT = { stem: "world-portrait", widths: [720, 1080] } as const;

/** Portrait crop below 768 px wide (keep in sync with hero.css). */
export const WORLD_PORTRAIT_MEDIA = "(max-width: 767px)";
export const WORLD_LANDSCAPE_MEDIA = "(min-width: 768px)";

/** The landscape plate covers the hero; it is never narrower than the viewport. */
export const WORLD_SIZES = "max(100vw, 160vh)";

export function worldSrcset(set: { stem: string; widths: readonly number[] }, format: "avif" | "webp"): string {
  return set.widths.map((w) => `/assets/hero/world/${set.stem}-${w}.${format} ${w}w`).join(", ");
}
