/**
 * Hero world images (generated by tooling/generate-hero-world.py into public/assets/hero/world).
 * Shared by HeroOrb (the <picture>) and the page head (a preload for the LCP image), so the
 * browser fetches exactly the file the layout uses.
 *
 * The hero's LCP element is the orb POSTER (Chrome treats the full-viewport plate as background).
 * Preload only the poster, one link per media, from POSTER_PRELOADS:
 *   {POSTER_PRELOADS.map((p) => (
 *     <link rel="preload" as="image" type="image/avif" fetchpriority="high"
 *           media={p.media} imagesrcset={p.srcset} imagesizes={p.sizes} />
 *   ))}
 * Do not preload the plate: it would compete with the poster for the first bytes.
 */
export const WORLD_LANDSCAPE = { stem: "world", widths: [1280, 1920, 2560] } as const;
export const WORLD_PORTRAIT = { stem: "world-portrait", widths: [720, 1080] } as const;

/** Portrait crop below 768 px wide (keep in sync with hero.css). */
export const WORLD_PORTRAIT_MEDIA = "(max-width: 767px)";
export const WORLD_LANDSCAPE_MEDIA = "(min-width: 768px)";

/** The landscape plate covers the hero; it is never narrower than the viewport. */
export const WORLD_SIZES = "max(100vw, 160vh)";

export function worldSrcset(set: { stem: string; widths: readonly number[] }, format: "avif" | "webp"): string {
  return set.widths.map((w) => `/assets/hero/world/${set.stem}-${w}.${format} ${w}w`).join(", ");
}

/** Orb poster (public/assets/hero/orb-<w>). Phones are capped at 768 (about 2.2x at their orb size). */
export const POSTER_WIDTHS = [384, 512, 640, 768, 1024] as const;
export const POSTER_MOBILE_MEDIA = "(max-width: 767px)";
export const POSTER_DESKTOP_MEDIA = "(min-width: 768px)";

/**
 * Poster sizes for the centered hero, matching the home layout's --hero-orb-max
 * (min(94vw, 42svh) below 768 px; min(44svh, 40vw, 40rem) above). Keep in sync with it.
 */
export const POSTER_SIZES_CENTERED = "(max-width: 767px) min(94vw, 42vh), min(44vh, 40vw, 640px)";

export function posterSrcset(format: "avif" | "webp", mobile = false): string {
  return POSTER_WIDTHS.filter((w) => !mobile || w <= 768)
    .map((w) => `/assets/hero/orb-${w}.${format} ${w}w`)
    .join(", ");
}

/** One AVIF preload per media, matching the poster's <source> elements exactly. */
export const POSTER_PRELOADS = [
  { media: POSTER_MOBILE_MEDIA, srcset: posterSrcset("avif", true), sizes: POSTER_SIZES_CENTERED },
  { media: POSTER_DESKTOP_MEDIA, srcset: posterSrcset("avif"), sizes: POSTER_SIZES_CENTERED },
] as const;
