/**
 * Game license signing (WebCrypto Ed25519) and the cross-language vectors the Unity verifier pins
 * (KalGame `Scripts/Runtime/Licensing/Tests~/game-license-vectors.json`).
 *
 * Regenerate after an intentional format change:
 *   UPDATE_GAME_VECTORS=1 pnpm --filter @kalcode/api exec vitest run tests/unit/game-license.test.ts
 * then copy the file to the game repo. Each regeneration uses a fresh throwaway key.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { GAME_LICENSE_TTL_SECONDS, type GameLicense } from "@kalcode/protocol/games";
import { describe, expect, it } from "vitest";
import { decodeBase64Url, encodeBase64Url, encodeBase64UrlText } from "../../worker/lib/base64url";
import { licenseSubject, signGameLicense, verifyGameLicense } from "../../worker/lib/game-license";
import { importPublicKey, signEntitlement } from "../../worker/lib/token";
import { generateSigningKey } from "../support/keys";
import { API_DIR } from "../support/wrangler";

const NOW = 1_791_000_000;
const VECTORS = join(API_DIR, "tests", "fixtures", "game-license-vectors.json");

async function sample(keyId: string, overrides: Partial<GameLicense> = {}): Promise<GameLicense> {
  return {
    version: 1,
    gameId: "kal_university",
    subject: await licenseSubject("acct_vector"),
    source: "max",
    perkTier: "max",
    perks: [
      { id: "ku_pro_headphones", kind: "wardrobe", ref: "acc_headphones", amountCents: 0 },
      { id: "ku_pro_retro_poster", kind: "decor", ref: "poster_retro_terminal", amountCents: 0 },
      { id: "ku_pro_start_cash", kind: "wallet", ref: "", amountCents: 5000 },
      { id: "ku_max_start_cash", kind: "wallet", ref: "", amountCents: 5000 },
    ],
    device: null,
    issuedAt: NOW,
    expiresAt: NOW + GAME_LICENSE_TTL_SECONDS,
    keyId,
    ...overrides,
  };
}

function flipLastSignatureBit(token: string): string {
  const [h, p, s = ""] = token.split(".");
  const bytes = decodeBase64Url(s) as Uint8Array;
  bytes[0] = (bytes[0] ?? 0) ^ 1;
  return `${h}.${p}.${encodeBase64Url(bytes)}`;
}

function swapPayload(token: string, payload: unknown): string {
  const [h, , s] = token.split(".");
  return `${h}.${encodeBase64UrlText(JSON.stringify(payload))}.${s}`;
}

describe("game license", () => {
  it("signs and verifies, with the subject never revealing the account id", async () => {
    const { key, trusted } = await generateSigningKey("g-unit");
    const license = await sample("g-unit");
    const token = await signGameLicense(license, key);
    const verified = await verifyGameLicense(token, trusted, NOW + 60);
    expect(verified).toEqual({ ok: true, license });
    expect(license.subject).not.toContain("acct_vector");
  });

  it("rejects tampering, unknown keys, expiry and a KalCode entitlement presented as a license", async () => {
    const { key, trusted } = await generateSigningKey("g-unit");
    const token = await signGameLicense(await sample("g-unit"), key);
    expect(await verifyGameLicense(flipLastSignatureBit(token), trusted, NOW)).toEqual({ ok: false, error: "bad_signature" });
    expect(await verifyGameLicense(swapPayload(token, await sample("g-unit", { perkTier: "max2x" })), trusted, NOW)).toEqual({
      ok: false,
      error: "bad_signature",
    });
    expect(await verifyGameLicense(token, new Map(), NOW)).toEqual({ ok: false, error: "unknown_key" });
    expect(await verifyGameLicense(token, trusted, NOW + GAME_LICENSE_TTL_SECONDS)).toEqual({ ok: false, error: "expired" });
    const entitlement = await signEntitlement(
      {
        version: 1,
        accountId: "acct_vector",
        tier: "max",
        unrestricted: false,
        features: [],
        limits: {},
        issuedAt: NOW,
        expiresAt: NOW + 3600,
        keyId: "g-unit",
      },
      key,
    );
    expect(await verifyGameLicense(entitlement, trusted, NOW)).toEqual({ ok: false, error: "unsupported_header" });
  });

  it("refuses to sign an invalid license", async () => {
    const { key } = await generateSigningKey("g-unit");
    await expect(signGameLicense(await sample("g-unit", { perkTier: "owner" as never }), key)).rejects.toThrow(/invalid/);
  });

  it("matches the committed cross-language vectors (verified again in Unity)", async () => {
    if (process.env.UPDATE_GAME_VECTORS === "1") {
      const { key } = await generateSigningKey("g-vector-1");
      const valid = await signGameLicense(await sample("g-vector-1"), key);
      const device = await signGameLicense(await sample("g-vector-1", { device: "Q".repeat(43), source: "standalone", perkTier: "standalone", perks: [] }), key);
      const vectors = {
        note: "Generated by apps/api/tests/unit/game-license.test.ts with a throwaway key. Never a production key.",
        keyId: "g-vector-1",
        publicKey: key.publicKey,
        now: NOW + 60,
        cases: [
          { name: "valid", token: valid, expect: "ok" },
          { name: "valid_device_bound", token: device, expect: "ok" },
          { name: "flipped_signature_bit", token: flipLastSignatureBit(valid), expect: "bad_signature" },
          { name: "tampered_payload", token: swapPayload(valid, await sample("g-vector-1", { perkTier: "max2x" })), expect: "bad_signature" },
          { name: "expired", token: valid, now: NOW + GAME_LICENSE_TTL_SECONDS, expect: "expired" },
          { name: "not_yet_valid", token: valid, now: NOW - 3600, expect: "not_yet_valid" },
          { name: "malformed", token: "abc.def", expect: "malformed" },
        ],
      };
      writeFileSync(VECTORS, `${JSON.stringify(vectors, null, 2)}\n`);
    }
    const vectors = JSON.parse(readFileSync(VECTORS, "utf8")) as {
      keyId: string;
      publicKey: string;
      now: number;
      cases: { name: string; token: string; now?: number; expect: string }[];
    };
    const publicKey = await importPublicKey(vectors.publicKey);
    expect(publicKey).not.toBeNull();
    const keys = new Map([[vectors.keyId, publicKey as CryptoKey]]);
    for (const vector of vectors.cases) {
      const result = await verifyGameLicense(vector.token, keys, vector.now ?? vectors.now);
      expect(result.ok ? "ok" : result.error, vector.name).toBe(vector.expect);
    }
  });
});
