// Every command the frontend may call. Tauri generates an `allow-<command>` permission for
// each; `capabilities/main.json` grants them to the trusted main webview. Anything not listed here is
// unreachable from the WebView.
include!("src/command_registry.rs");

/// Test hooks. Declared (and so given an `allow-*` permission) only when the target build has
/// test hooks compiled in: debug builds and the `e2e` feature. Release builds don't register
/// these commands at all; their grant lives in `test-capabilities/test-hooks.json`, which the app
/// adds at runtime under the same condition. Never listed in `capabilities/`.
const TEST_HOOK_COMMANDS: &[&str] = &["test_permission_probe"];

/// Whether the crate being built has test hooks (`cfg!(any(debug_assertions, feature = "e2e"))`
/// in the crate). A build script's own `cfg!` describes the build script, so read Cargo's view
/// of the target instead.
fn target_has_test_hooks() -> bool {
    std::env::var_os("CARGO_CFG_DEBUG_ASSERTIONS").is_some()
        || std::env::var_os("CARGO_FEATURE_E2E").is_some()
}

/// Tauri's Windows dialog runtime imports `TaskDialogIndirect`, which exists only in Common
/// Controls v6. Packaged app executables receive Tauri's normal Windows resources, but Cargo's
/// native test harnesses do not. Cargo's test-only linker directive does not reach a library unit
/// test harness, so debug MSVC targets receive the activation dependency. Release packaging stays
/// entirely under Tauri's normal resource generation.
fn configure_windows_debug_manifest(debug: bool) {
    let target_os = std::env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
    let target_env = std::env::var("CARGO_CFG_TARGET_ENV").unwrap_or_default();
    if debug && target_os == "windows" && target_env == "msvc" {
        let output = std::path::PathBuf::from(
            std::env::var_os("OUT_DIR")
                .unwrap_or_else(|| panic!("Cargo did not provide OUT_DIR for the test manifest")),
        )
        .join("common-controls-v6.manifest");
        std::fs::write(
            &output,
            br#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <dependency><dependentAssembly><assemblyIdentity type="win32" name="Microsoft.Windows.Common-Controls" version="6.0.0.0" processorArchitecture="*" publicKeyToken="6595b64144ccf1df" language="*"/></dependentAssembly></dependency>
</assembly>
"#,
        )
        .unwrap_or_else(|error| panic!("could not write {}: {error}", output.display()));
        println!("cargo:rustc-link-arg=/MANIFEST:EMBED");
        println!("cargo:rustc-link-arg=/MANIFESTINPUT:{}", output.display());
        // Tauri links its own compiled manifest resource into application binaries. Suppress
        // linker-generated manifests there so this unit-harness input cannot duplicate or replace
        // the packaged identity resource.
        println!("cargo:rustc-link-arg-bins=/MANIFEST:NO");
        println!("cargo:rustc-link-arg-bins=/IGNORE:4075");
    }
}

fn main() {
    // Fail closed for direct Cargo/CLI invocations that omit the Dev overlay. This also
    // prevents a release binary (and its credential service) using a Dev bundle identity.
    println!("cargo:rerun-if-env-changed=TAURI_CONFIG");
    let debug = std::env::var_os("CARGO_CFG_DEBUG_ASSERTIONS").is_some();
    configure_windows_debug_manifest(debug);
    let base: serde_json::Value = serde_json::from_str(include_str!("tauri.conf.json"))
        .unwrap_or_else(|error| panic!("invalid base app config: {error}"));
    let overlay: serde_json::Value =
        serde_json::from_str(&std::env::var("TAURI_CONFIG").unwrap_or_else(|_| "{}".into()))
            .unwrap_or_else(|error| panic!("invalid TAURI_CONFIG: {error}"));
    let expected: serde_json::Value = if debug {
        serde_json::from_str(include_str!("tauri.dev.conf.json"))
            .unwrap_or_else(|error| panic!("invalid Dev app config: {error}"))
    } else {
        base.clone()
    };
    for path in [
        "/identifier",
        "/productName",
        "/plugins/deep-link/desktop/schemes",
    ] {
        let actual = overlay.pointer(path).or_else(|| base.pointer(path));
        assert_eq!(
            actual,
            expected.pointer(path),
            "app identity/profile mismatch at {path}; use pnpm tauri dev/build, or set TAURI_CONFIG to the Dev overlay for direct debug Cargo commands"
        );
    }
    println!("cargo:rerun-if-changed=test-capabilities");
    println!("cargo:rerun-if-env-changed=KALCODE_AUTHENTICODE_IDENTITY_OIDS");
    let mut commands = COMMANDS.to_vec();
    if target_has_test_hooks() {
        commands.extend_from_slice(TEST_HOOK_COMMANDS);
    } else {
        // tauri-build loads every file in `permissions/autogenerated/`, and a debug build of
        // this checkout leaves the test hooks' files there (git-ignored). Remove them so a
        // release build doesn't even define their permissions.
        for command in TEST_HOOK_COMMANDS {
            let stale =
                std::path::Path::new("permissions/autogenerated").join(format!("{command}.toml"));
            if let Err(error) = std::fs::remove_file(&stale)
                && error.kind() != std::io::ErrorKind::NotFound
            {
                eprintln!("couldn't remove {}: {error}", stale.display());
                std::process::exit(1);
            }
        }
    }
    let commands: &'static [&'static str] = commands.leak();
    let attributes = tauri_build::Attributes::new()
        .app_manifest(tauri_build::AppManifest::new().commands(commands));
    if let Err(error) = tauri_build::try_build(attributes) {
        eprintln!("tauri build script failed: {error:#}");
        std::process::exit(1);
    }
}
